services:
  db:
    image: ankane/pgvector:latest
    container_name: postgres_pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: change_pass
      POSTGRES_DB: news_article_agent
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
